# Generated by Django 5.1.7 on 2026-04-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncOperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_operation_id", models.CharField(max_length=100, unique=True)),
                ("operation", models.CharField(max_length=20)),
                (
                    "transaction_id",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("payload_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("applied", "Applied"), ("failed", "Failed")],
                        max_length=10,
                    ),
                ),
                ("message", models.CharField(blank=True, default="", max_length=255)),
                ("fields", models.JSONField(blank=True, default=dict)),
                ("server_synced_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-server_synced_at"],
            },
        ),
    ]
