# Generated by Codex on 2026-04-21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0002_syncoperationlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="financial_nature",
            field=models.CharField(
                choices=[
                    ("spending", "Spending"),
                    ("saving", "Saving"),
                    ("investment", "Investment"),
                ],
                default="spending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="budget_group_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="goal_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="FinancialGoal",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_archived", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
